# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - echo 'Update here'
  fmt:
    cmds:
      - typos . .github .vscode --write-changes
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      - git ls-files '*.nix' | xargs nixfmt --check
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - tesseract --version
      - img2pdf --version
      - pngquant --version
